const APP_URL = window.GOOGLE_APPS_SCRIPT_URL || '';
const $ = id => document.getElementById(id);
const today = new Date();
const isoDate = new Date(today.getTime() - today.getTimezoneOffset()*60000).toISOString().slice(0,10);
$('todayDisplay').textContent = new Intl.DateTimeFormat('fr-FR').format(today);
$('dateReprise').value = isoDate;

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function addMaterial(values={}){
  const tr=document.createElement('tr');
  tr.innerHTML=`<td><input class="name-input" type="text" value="${escapeHtml(values.name||'')}" placeholder="Nom"></td><td><input class="qty-input" type="number" min="0" step="1" value="${escapeHtml(values.quantity||'1')}" inputmode="numeric"></td><td><input class="product-input" type="text" value="${escapeHtml(values.product||'')}" placeholder="Dénomination du matériel"></td><td><input class="serial-input" type="text" value="${escapeHtml(values.serial||'')}" placeholder="N° de série / lot"></td><td><input class="state-input" type="text" value="${escapeHtml(values.state||'')}" placeholder="Bon état, usé…"></td><td class="remove-col"><button type="button" class="remove" title="Supprimer">×</button></td>`;
  tr.querySelector('.remove').onclick=()=>{if(document.querySelectorAll('#materialsBody tr').length>1)tr.remove()};
  $('materialsBody').appendChild(tr);
}
addMaterial();$('addMaterial').onclick=()=>addMaterial();

function setupSignature(canvasId,clearId){
  const c=$(canvasId),ctx=c.getContext('2d');let drawing=false,last=null;
  function resize(){const ratio=window.devicePixelRatio||1,rect=c.getBoundingClientRect(),old=c.toDataURL();c.width=Math.max(1,Math.round(rect.width*ratio));c.height=Math.max(1,Math.round(rect.height*ratio));ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#173b63';if(old&&old!=='data:,'){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,rect.width,rect.height);img.src=old}}
  resize();window.addEventListener('resize',resize);
  c.addEventListener('pointerdown',e=>{drawing=true;last=[e.offsetX,e.offsetY];c.setPointerCapture(e.pointerId)});
  c.addEventListener('pointermove',e=>{if(!drawing)return;ctx.beginPath();ctx.moveTo(last[0],last[1]);ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke();last=[e.offsetX,e.offsetY]});
  ['pointerup','pointercancel','pointerleave'].forEach(ev=>c.addEventListener(ev,()=>drawing=false));
  $(clearId).onclick=()=>ctx.clearRect(0,0,c.width,c.height);return c;
}
const patientSignature=setupSignature('patientSignature','clearPatientSignature');
const technicianSignature=setupSignature('technicianSignature','clearTechnicianSignature');
function hasInk(c){const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=3;i<d.length;i+=4)if(d[i]>10)return true;return false}

function collect(){
 const materials=[...document.querySelectorAll('#materialsBody tr')].map(tr=>({name:tr.querySelector('.name-input').value.trim(),quantity:tr.querySelector('.qty-input').value.trim(),product:tr.querySelector('.product-input').value.trim(),serial:tr.querySelector('.serial-input').value.trim(),state:tr.querySelector('.state-input').value.trim()})).filter(x=>x.name||x.product||x.serial||x.state);
 const motif=document.querySelector('input[name="motif"]:checked')?.value||'';
 return {date:$('dateReprise').value,patient:{nom:$('patientNom').value.trim(),prenom:$('patientPrenom').value.trim(),adresse:$('patientAdresse').value.trim(),tel:$('patientTel').value.trim(),etab:$('patientEtab').value.trim(),email:$('patientEmail').value.trim()},materials,motif:motif==='Autre'?($('motifAutre').value.trim()||'Autre'):motif,anomaly:$('anomalie').checked,observations:$('observations').value.trim(),photos:window.REPRISE_PHOTOS||[],technician:$('technicien').value.trim(),patientSig:patientSignature.toDataURL('image/png'),techSig:technicianSignature.toDataURL('image/png')};
}
function validateData(){const d=collect();if(!d.patient.nom&&!d.patient.prenom){alert('Renseignez le nom du patient / client.');$('patientNom').focus();return null}if(!d.materials.length){alert('Ajoutez au moins un matériel repris.');return null}if(d.materials.some(x=>!x.product)){alert('Chaque ligne utilisée doit comporter la dénomination du matériel repris.');return null}if(!d.motif){alert('Sélectionnez le motif de reprise.');return null}if(!d.technician){alert('Renseignez le nom du technicien EuroMed.');$('technicien').focus();return null}if(!hasInk(patientSignature)){alert('La signature du patient / représentant est nécessaire pour valider le bon.');return null}if(!hasInk(technicianSignature)){alert('La signature du technicien EuroMed est nécessaire pour valider le bon.');return null}return d}

$('anomalie').onchange=()=>{$('photoArea').classList.toggle('hidden',!$('anomalie').checked);if(!$('anomalie').checked){window.REPRISE_PHOTOS=[];$('photoInput').value='';$('photoPreview').innerHTML=''}};
document.querySelectorAll('input[name="motif"]').forEach(r=>r.onchange=()=>{$('motifAutre').classList.toggle('hidden',r.value!=='Autre'||!r.checked)});
window.REPRISE_PHOTOS=[];
async function compressPhoto(file){const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=data});const max=1400,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)}
$('photoInput').onchange=async e=>{const files=[...e.target.files||[]];try{for(const f of files)window.REPRISE_PHOTOS.push(await compressPhoto(f));renderPhotos()}catch(err){console.error(err);alert('Impossible de traiter une photo.')}};
function renderPhotos(){$('photoPreview').innerHTML='';window.REPRISE_PHOTOS.forEach((src,i)=>{const wrap=document.createElement('div');wrap.style.position='relative';const img=document.createElement('img');img.src=src;img.alt='Photo '+(i+1);wrap.appendChild(img);const b=document.createElement('button');b.type='button';b.textContent='×';b.title='Supprimer';b.style.cssText='position:absolute;right:4px;top:4px;width:30px;height:30px;border:0;border-radius:50%;background:rgba(20,50,65,.78);color:#fff;font-size:20px;cursor:pointer';b.onclick=()=>{window.REPRISE_PHOTOS.splice(i,1);renderPhotos()};wrap.appendChild(b);$('photoPreview').appendChild(wrap)})}

let jsPdfPromise=null;
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Impossible de charger '+src));document.head.appendChild(s)})}
async function ensurePdfLibrary(){if(window.jspdf?.jsPDF)return window.jspdf.jsPDF;if(!jsPdfPromise){jsPdfPromise=(async()=>{for(const src of ['https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js']){try{await loadScript(src);if(window.jspdf?.jsPDF)return window.jspdf.jsPDF}catch(e){}}throw new Error('La bibliothèque PDF n’a pas pu être chargée.')})()}return jsPdfPromise}
function formatDate(s){if(!s)return'—';const[y,m,d]=s.split('-');return d&&m&&y?`${d}/${m}/${y}`:s}
function imageData(url){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=url})}
function footer(pdf,page){pdf.setDrawColor(190,213,222);pdf.line(12,286,198,286);pdf.setFont('helvetica','normal');pdf.setFontSize(6.8);pdf.setTextColor(96,119,132);pdf.text('EuroMed · +33.327.64.34.99 · www.euromed-materiel-medical.com',12,291);pdf.text('117 rue de Maubeuge · F-59620 Aulnoye-Aymeries',105,291,{align:'center'});pdf.text(`Page ${page}`,198,291,{align:'right'})}
function section(pdf,title,y){pdf.setFillColor(7,87,127);pdf.roundedRect(12,y,186,7,1.5,1.5,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.setTextColor(255,255,255);pdf.text(title,16,y+4.8);return y+10}
function safeImage(pdf,data,fmt,x,y,w,h){try{if(data)pdf.addImage(data,fmt,x,y,w,h)}catch(e){}}
async function buildPdf(d){const jsPDF=await ensurePdfLibrary();const pdf=new jsPDF({unit:'mm',format:'a4',compress:true});const blue=[7,125,181],navy=[18,59,90],pale=[231,244,247],line=[193,215,223],text=[28,52,66],muted=[92,117,130];let page=1;let y=49;const newPage=()=>{footer(pdf,page);pdf.addPage();page++;return 16};const ensure=n=>y+n>278?(y=newPage()):y;
 pdf.setFillColor(...pale);pdf.roundedRect(10,9,190,34,3,3,'F');pdf.setFillColor(...blue);pdf.roundedRect(10,9,5,34,2,2,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(23);pdf.setTextColor(...navy);pdf.text('BON DE REPRISE',20,22);pdf.setFont('helvetica','normal');pdf.setFontSize(8.5);pdf.setTextColor(...muted);pdf.text('Document de reprise · EuroMed',20,28);pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.setTextColor(...navy);pdf.text('DATE DU JOUR',20,36);pdf.setFontSize(10);pdf.text(formatDate(d.date),52,36);try{const logo=await imageData('euromed-logo.jpeg');pdf.addImage(logo,'JPEG',135,12,61,16)}catch(e){}pdf.setFont('helvetica','normal');pdf.setFontSize(7.2);pdf.setTextColor(...muted);pdf.text('+33.327.64.34.99',198,31,{align:'right'});pdf.text('www.euromed-materiel-medical.com',198,35,{align:'right'});pdf.text('117 rue de Maubeuge · F-59620 Aulnoye-Aymeries',198,39,{align:'right'});
 y=section(pdf,'PATIENT / CLIENT',y);pdf.setDrawColor(...line);pdf.setFillColor(250,253,254);pdf.roundedRect(12,y,186,35,2,2,'FD');pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.setTextColor(...navy);pdf.text('NOM / PRÉNOM',17,y+7);pdf.text('ADRESSE',17,y+16);pdf.text('TÉLÉPHONE',113,y+16);pdf.text('ÉTABLISSEMENT / SERVICE',17,y+25);pdf.text('E-MAIL',113,y+25);pdf.setFont('helvetica','normal');pdf.setFontSize(8.5);pdf.setTextColor(...text);pdf.text(`${d.patient.nom||'—'} ${d.patient.prenom||''}`.trim(),17,y+11);pdf.text(d.patient.adresse||'—',17,y+20);pdf.text(d.patient.tel||'—',113,y+20);pdf.text(d.patient.etab||'—',17,y+29);pdf.text(d.patient.email||'—',113,y+29);y+=43;
 y=section(pdf,'MATÉRIEL REPRIS',y);const hx=[14,43,58,126,163],headers=['Nom','Qté','Dénomination du matériel repris','N° de série / lot','État'];pdf.setFillColor(...pale);pdf.rect(12,y,186,9,'FD');pdf.setFont('helvetica','bold');pdf.setFontSize(7.2);pdf.setTextColor(...navy);headers.forEach((h,i)=>pdf.text(h,hx[i],y+5.7));y+=9;pdf.setFont('helvetica','normal');pdf.setFontSize(7.8);pdf.setTextColor(...text);d.materials.forEach((m,i)=>{const a=[m.name||'—',m.quantity||'1',m.product||'—',m.serial||'—',m.state||'—'];const ws=[27,13,65,35,31];const ls=a.map((v,j)=>pdf.splitTextToSize(v,ws[j]-3).slice(0,3));const h=Math.max(9,...ls.map(z=>z.length*3.5+4));if(y+h>278){y=newPage();y=section(pdf,'MATÉRIEL REPRIS — SUITE',y);pdf.setFillColor(...pale);pdf.rect(12,y,186,9,'FD');headers.forEach((h0,k)=>pdf.text(h0,hx[k],y+5.7));y+=9}if(i%2){pdf.setFillColor(249,252,253);pdf.rect(12,y,186,h,'F')}pdf.setDrawColor(...line);pdf.rect(12,y,186,h);[43,58,126,163].forEach(x=>pdf.line(x,y,x,y+h));ls.forEach((z,j)=>pdf.text(z,hx[j],y+4));y+=h});y+=7;
 y=ensure(38);y=section(pdf,'MOTIF DE REPRISE',y);pdf.setFillColor(250,253,254);pdf.setDrawColor(...line);pdf.roundedRect(12,y,186,17,2,2,'FD');pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.setTextColor(...navy);pdf.text(d.motif||'Non renseigné',17,y+10);y+=24;
 y=ensure(48);y=section(pdf,'ÉTAT / OBSERVATIONS',y);pdf.setFont('helvetica','bold');pdf.setFontSize(8.5);pdf.setTextColor(...(d.anomaly?[185,54,54]:[29,125,96]));pdf.text(d.anomaly?'ANOMALIE OU DOMMAGE CONSTATÉ':'Aucune anomalie signalée',17,y+1);y+=6;pdf.setFont('helvetica','normal');pdf.setTextColor(...text);const obs=pdf.splitTextToSize(d.observations||'Aucune observation.',178),oh=Math.max(22,obs.length*4+8);pdf.setFillColor(250,253,254);pdf.roundedRect(12,y,186,oh,2,2,'FD');pdf.text(obs,16,y+7);y+=oh+7;if(d.photos.length){y=ensure(62);pdf.setFont('helvetica','bold');pdf.setTextColor(...navy);pdf.text('PHOTOS DE L’ANOMALIE',17,y+2);y+=6;for(let i=0;i<d.photos.length;i++){if(y+52>278)y=newPage();safeImage(pdf,d.photos[i],'JPEG',17,y,55,42);y+=47}}
 y=ensure(100);y=section(pdf,'RÉCEPTION DE LA REPRISE',y);pdf.setFillColor(...pale);pdf.roundedRect(12,y,186,13,2,2,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(10.5);pdf.setTextColor(...navy);pdf.text('Matériel repris par EuroMed',105,y+8.3,{align:'center'});y+=18;pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.text('TECHNICIEN EUROmed'.toUpperCase(),14,y);pdf.text('DATE',150,y);pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.setTextColor(...text);pdf.text(d.technician||'—',14,y+6);pdf.text(formatDate(d.date),150,y+6);y+=13;pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);pdf.setTextColor(...muted);pdf.text('Je soussigné(e), reconnais avoir remis à EuroMed le matériel indiqué sur le présent bon de reprise.',14,y+2);y+=9;pdf.setFillColor(248,251,252);pdf.setDrawColor(...line);pdf.roundedRect(12,y,90,57,2,2,'FD');pdf.roundedRect(108,y,90,57,2,2,'FD');pdf.setFont('helvetica','bold');pdf.setFontSize(8.5);pdf.setTextColor(...navy);pdf.text('SIGNATURE DU PATIENT / REPRÉSENTANT',57,y+7,{align:'center'});pdf.text('SIGNATURE DU TECHNICIEN EUROMED',153,y+7,{align:'center'});pdf.setDrawColor(...line);pdf.rect(17,y+12,80,39);pdf.rect(113,y+12,80,39);safeImage(pdf,d.patientSig,'PNG',19,y+14,76,35);safeImage(pdf,d.techSig,'PNG',115,y+14,76,35);footer(pdf,page);return pdf}
async function pdfBase64(d){const pdf=await buildPdf(d);return pdf.output('datauristring').split(',')[1]}
function filename(d){const n=(d.patient.nom||'Client').replace(/[^a-z0-9_-]/gi,'_');return `Bon_de_reprise_${n}_${d.date}.pdf`}
function dataUriToBase64(s){return s?s.split(',')[1]||'':''}
let currentData=null,currentPdfBase64=null;
$('validate').onclick=async()=>{const d=validateData();if(!d)return;currentData=d;$('modalClientEmail').value=d.patient.email;$('sendClient').checked=!!d.patient.email;currentPdfBase64=null;$('sendStatus').textContent='Génération du bon de reprise…';$('sendModal').classList.remove('hidden');try{currentPdfBase64=await pdfBase64(d);$('sendStatus').textContent='✓ Bon prêt. Choisissez les options d’envoi.'}catch(e){console.error(e);$('sendStatus').innerHTML='<span class="error">Erreur lors de la génération du PDF : '+escapeHtml(e.message)+'</span>'}};
$('sendClient').onchange=()=>{$('clientEmailWrap').style.opacity=$('sendClient').checked?'1':'.55'};$('clientEmailWrap').style.opacity=$('sendClient').checked?'1':'.55';$('closeModal').onclick=()=>$('sendModal').classList.add('hidden');
$('downloadPdf').onclick=async()=>{if(!currentData)return;try{if(!currentPdfBase64)currentPdfBase64=await pdfBase64(currentData);const a=document.createElement('a');a.href='data:application/pdf;base64,'+currentPdfBase64;a.download=filename(currentData);a.click()}catch(e){$('sendStatus').innerHTML='<span class="error">Impossible de générer le PDF : '+escapeHtml(e.message)+'</span>'}};
$('sendNow').onclick=async()=>{if(!currentData||!currentPdfBase64)return;if(!APP_URL){$('sendStatus').innerHTML='<span class="error">URL Google Apps Script absente dans config.js.</span>';return}const sendClient=$('sendClient').checked,email=$('modalClientEmail').value.trim();if(sendClient&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('sendStatus').innerHTML='<span class="error">Renseignez une adresse e-mail client valide.</span>';return}$('sendNow').disabled=true;$('sendStatus').textContent='Envoi en cours…';try{const payload={action:'send_reprise',filename:filename(currentData),pdf_base64:currentPdfBase64,data:JSON.stringify({...currentData,patient:{...currentData.patient,email}}),send_client:sendClient?'1':'0'};const res=await fetch(APP_URL,{method:'POST',body:new URLSearchParams(payload)});const result=await res.json();if(!result.ok)throw new Error(result.error||'Erreur serveur');$('sendStatus').innerHTML='<span class="success">✓ Bon de reprise envoyé automatiquement à EuroMed'+(sendClient?' et au client.':'.')+'</span>';$('status').textContent='Bon de reprise validé et envoyé.'}catch(e){console.error(e);$('sendStatus').innerHTML='<span class="error">Échec de l’envoi : '+escapeHtml(e.message)+'</span>'}finally{$('sendNow').disabled=false}};
